version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    groups:
      containers:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
    groups:
      compose-containers:
        patterns: ["*"]
    open-pull-requests-limit: 5
